#spring.datasource.platform: postgres
#spring.datasource.driverClassName: org.postgresql.Driver
#spring.datasource.url: jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username: postgres
#spring.datasource.password: password
##    url: jdbc:postgresql://pg:5432/studs
##    username: s288870
##    password: qta730
#    jpa:
#      database: POSTGRESQL
#      hibernate:
#        ddl-auto: none

spring.datasource.url: jdbc:postgresql://localhost:5432/postgres
spring.datasource.username: postgres
spring.datasource.password: password

spring.jpa.database: POSTGRESQL
#spring.jpa.hibernate.ddl-auto:none


camunda.bpm.admin-user:
  id: demo
  password: demo